### ISSUE TITLE
机器人在接收到消息后报错AttributeError: 'GroupMessage' object has no attribute 'at_ _me'. Did you mean: ' time' ?

### ISSUE THREAD

**Issue by wjiajian** [MuBai-He/ChatWaifu-marai#13]
![image](https://user-images.githubusercontent.com/71640797/211730837-bc53686b-fca1-41c6-a446-9b542fb7795f.png)
如图在收到任何消息后都会报这个错，而且收到@消息后无任何反应

**Comment by MuBai-He** [comment]
感觉是miraicle的问题，重新安装下试试

**Comment by wjiajian** [comment]
> miraicle

好的，问题已解决
