### ISSUE TITLE
发送问题后，浏览器里的答案没有被回复，也没有语音

### ISSUE THREAD

**Issue by rightzebra** [MuBai-He/ChatWaifu-marai#33]
终端状态如下，但是会有回复，但是api的，不是浏览器里的
![image](https://user-images.githubusercontent.com/61533762/231920770-251e6556-6eed-4fa4-ac72-4d489b37ee98.png)
聊天记录如下
![0D(BP AP9Q30_PI75P$UY@V](https://user-images.githubusercontent.com/61533762/231921255-72358cfc-3bad-44bd-a16b-09ef474f77fd.png)
而且私聊也不会回复

**Comment by MuBai-He** [comment]
pychatgpt有问题，后期尽量更新api版本

**Comment by rightzebra** [comment]
好的
