### ISSUE TITLE
大佬

### ISSUE THREAD

**Issue by the-lazy-me** [MuBai-He/ChatWaifu-marai#4]
这个是不是因为cloudflare验证没通过，用不了？
![Snipaste_2022-12-20_12-09-30](https://user-images.githubusercontent.com/52873503/208582373-aef9b49b-e9f8-4047-ac36-746264f73f0e.png)

**Comment by MuBai-He** [comment]
这个是qq机器人版本，请检查文件开头信息填写是否正确

**Comment by the-lazy-me** [comment]
配置应该是正确了吧？但是还是报错
![Snipaste_2022-12-20_15-00-29](https://user-images.githubusercontent.com/52873503/208603556-158d72ea-c05a-4504-8a85-3e6814dd0aaa.png)
![Snipaste_2022-12-20_15-01-06](https://user-images.githubusercontent.com/52873503/208603565-16df60eb-e756-497a-a7ec-41a520c9eb81.png)

**Comment by greenthree** [comment]
setting文件中cachesize下一行加上

> persistenceFactory: 'built-in'

**Comment by the-lazy-me** [comment]
感谢大佬，折腾了一下午，查了mirai官方文档，已经用上啦

**Comment by xlbl** [comment]
请问你是怎么解决的呢？我遇到这个问题了

**Comment by the-lazy-me** [comment]
> 请问你是怎么解决的呢？我遇到这个问题了

https://www.bilibili.com/video/BV1ue4y1G7aF/

**Comment by xlbl** [comment]
我已经看过这个视频了，但是还是没有解决，报错10061计算机积极拒绝。

**Comment by xlbl** [comment]
verifyKey和端口设置一致了，还是没有成功。

**Comment by the-lazy-me** [comment]
> verifyKey和端口设置一致了，还是没有成功。

mirai收信息正常不？

**Comment by xlbl** [comment]
我是第一次使用mirai,可以正常收到QQ消息，就是没有提示这个
![image](https://user-images.githubusercontent.com/70011824/211234988-eedb6f1b-a71d-47b4-b40f-1d04a6c71a29.png)

**Comment by xlbl** [comment]
我怀疑是我的mirai的问题，不知道使用什么命令来启动

**Comment by the-lazy-me** [comment]
> 我怀疑是我的mirai的问题，不知道使用什么命令来启动

mirai那里什么报错？

**Comment by xlbl** [comment]
没有报错

**Comment by the-lazy-me** [comment]
> 没有报错

mirai正常运行是会有这个的

**Comment by xlbl** [comment]
![image](https://user-images.githubusercontent.com/70011824/211235361-28a7a07b-e55d-4ab1-b45b-854df4ff3b00.png)
这个应该不是报错吧

**Comment by the-lazy-me** [comment]
> 没有报错

mirai正常运行是会有这个的

**Comment by xlbl** [comment]
眼瞎了

**Comment by MuBai-He** [comment]
这不是都没登录吗

**Comment by xlbl** [comment]
![image](https://user-images.githubusercontent.com/70011824/211235548-2929ba37-7de6-4abe-af18-2f6606ca81c9.png)

**Comment by xlbl** [comment]
解决了，原来要先启动marai
